### PR TITLE
Count dois not indexed by repository

### PR DESCRIPTION
**Pull request by mfenner**
## Purpose
Generate a listing of DOIs not indexed by repositories.

## Approach
Loop through all repositories and count number of DOIs in db and Elasticsearch. List repository if there is a difference with total number of dois and number missing.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by mfenner** [comment]
The commit https://github.com/datacite/lupo/commit/b16a04577b0313c9ed2b38995d5e872cbc67a06c didn't make it into the pull request, but includes the rake task that triggers the report generation.

**Review by richardhallett — APPROVED** [review]
Looks fine, will be quite slow doing a individual query for each client count, but without a different index on the DB this probably is the easiest route.

**Comment by mfenner** [comment]
@richardhallett I briefly looked into MySQL `group by`. This can dramatically cut down on the number of queries, but be a very big query.

**Comment by richardhallett** [comment]
> @richardhallett I briefly looked into MySQL `group by`. This can dramatically cut down on the number of queries, but be a very big query.

A group by would be the canonical and probably preferred way to do this, saves the IO round trip, and SQL is better at grouping, however without an index on the datacentre its probably not going to be that efficient given size of our DB:)

**Pull request merged**
