### PR TITLE
added created aggregation for events endpoint

### PR DESCRIPTION
**Pull request by kjgarza**
its difficult to see if events from crossref or event datacie have been created lated and where the gaps happen. the occured aggregation only focuses on when the events dates were generated but no when they were captured. this aggregation is more useful to identify problems with collection.

## Purpose

closes: _Add github issue that originated this PR_

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by kjgarza** [comment]
True I'll add some

**Comment by jrhoads** [comment]
@kjgarza Looks like it currently fails the first expect statement.

**Comment by kjgarza** [comment]
yeah i know :D i haven't send the review request yet heheh; I'll send it later

**Comment by jrhoads** [comment]
Ahh.  I understand now.  :-)

**Pull request merged**
