### PR TITLE
Add Service Provider integrations to repository software list

### PR DESCRIPTION
**Pull request by KellyStathis**
## Purpose

Updates list to align with https://github.com/datacite/bracco/pull/720.

#### Open Questions and Pre-Merge TODOs
- [ ] should be merged after https://github.com/datacite/bracco/pull/720
- [ ] refresh API Reference in ReadMe

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by svogt0511** [comment]
Looks good.  I tested this with the bracco mod that corresponds with this and it seems to work fine.

Several things which we can talk about:

- [ ] Why do you think you should merge this after datacite/bracco#720?  Actually, you should merge and deploy this first, before your bracco change.  Doing that would allow you to test bracco without having to set up lupo locally.
- [ ] update-repo-software is an old branch.  You need to rebase this branch to the head of lupo master, push it to github, and allow the pull request to run the test suite on this branch.  When the test suite passes you can close this pull request.
- [ ] What readme do you have to update?

**Comment by KellyStathis** [comment]
Thanks for reviewing, @svogt0511!

This change only affects the openapi.yaml file which to my knowledge is only used by our support site's API reference tool: https://support.datacite.org/reference/get_clients. The software used by our support site is called "ReadMe" (https://dash.readme.com/).

I'm not sure how to do a rebase. I know how to merge changes from master into this branch - would that work?

As far as software dependencies, I don't think the order these changes are merged should matter much as this isn't a substantive change to lupo! My suggestion that it should be merged after was more so that until users can update the repository software to these new values in Fabrica, the API reference shouldn't suggest retrieving clients based on these values.

**Comment by svogt0511** [comment]
@KellyStathis - Apparently you can rebase from this page! This should work since there should be no conflicts. (Pick 'rebase and merge').  I usually do it from the command line but this should be easy enough!

image

**Comment by svogt0511** [comment]
@KellyStathis Also, merging to lupo first allows you to move your lupo changes to staging, then makes it much easier for you to test your bracco changes.

**Comment by KellyStathis** [comment]
Thanks @svogt0511! I don't think I'm authorized to merge (which makes sense for my role) - do you have the option to? thanks!

Screen Shot 2023-05-01 at 11 43 43

**Comment by KellyStathis** [comment]
Forgot this was still open. With refactoring openapi.yaml in progress, I thought it would just be easier to make this change on that pull request: https://github.com/datacite/lupo/pull/964. Closing this one without merging.

**Pull request closed without merging**
