### PR TITLE
Refactor updating terraform into a callable component.

### PR DESCRIPTION
**Pull request by jrhoads**
## Purpose
This PR refactors in the deploy and release action to use a common update_terraform action.
This is in preparation for further work that will have a manual deploy trigger for non-main/master branches to staging.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Review by digitaldogsbody — APPROVED** [review]
Looks good to me, nice refactor :)

**Comment by jrhoads** [comment]
I like the idea of sed replacement.  Dockerize seemed a bit much for a templating solution.

**Comment by digitaldogsbody** [comment]
+1 to sed

**Comment by jrhoads** [comment]
Since we use it so often, do you think there would be a value in adding the sed command as a script in the mastino repository?

**Pull request merged**
